version: "3.6"
services:
  phpunit-php55:
    build:
      context: .
      args:
        - COMPOSER_AUTH
        - PHP_VERSION=5.5.38
    user: $DOCKER_USER
    volumes:
      - .:/app
      - /app/vendor

  phpunit-php56:
    build:
      context: .
      args:
        - COMPOSER_AUTH
        - PHP_VERSION=5.6.40
    user: $DOCKER_USER
    volumes:
      - .:/app
      - /app/vendor

  phpunit-php70:
    build:
      context: .
      args:
        - COMPOSER_AUTH
        - PHP_VERSION=7.0.33
    user: $DOCKER_USER
    volumes:
      - .:/app
      - /app/vendor

  phpcs:
    build:
      dockerfile: Dockerfile-phpcs
      context: .
    user: $DOCKER_USER
    volumes:
      - .:/app
      - /app/vendor
      - ./reports:/app/reports
