name: Run PHPCompatibility checks

on:
  pull_request:
    branches: [ main ]

jobs:
  php-compatibility-check:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.1', '7.2', '7.3', '7.4', '8.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          extensions: tokenizer, xmlwriter, SimpleXML, mycrypt
          ini-values: max_execution_time=0, memory_limit=-1
          coverage: none
          tools: cs2pr, phpcs, phpcompatibility/php-compatibility
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure PHP CodeSniffer - setup PHPCompatibility rules
        run: |
          phpcs \
            --config-set installed_paths ${HOME}/.composer/vendor/phpcompatibility/php-compatibility/PHPCompatibility \
            -i

      - name: Run Stylecheck with PHP CodeSniffer
        run: |
          git diff --name-only --diff-filter=d origin/main...HEAD > filelist.txt
          ls -al filelist.txt
          phpcs \
              -q \
              --file-list=filelist.txt \
              --extensions=php \
              --report=checkstyle \
              --standard=PHPCompatibility \
              --runtime-set testVersion ${{ matrix.php-versions }} | cs2pr
