name: Run tests on PR

on:
  pull_request:
    branches:
      - main

jobs:
  test-php:
    runs-on: ubuntu-latest
    steps:
      - uses: hNczy/test-php@test
        with:
          php-versions: '["5.5", "5.6", "7.0"]'
